package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"github.com/thanishsid/dingilink-server/api/graphql/generated"
)

// Mutations returns generated.MutationsResolver implementation.
func (r *Resolver) Mutations() generated.MutationsResolver { return &mutationsResolver{r} }

// Queries returns generated.QueriesResolver implementation.
func (r *Resolver) Queries() generated.QueriesResolver { return &queriesResolver{r} }

// Subscriptions returns generated.SubscriptionsResolver implementation.
func (r *Resolver) Subscriptions() generated.SubscriptionsResolver { return &subscriptionsResolver{r} }

type mutationsResolver struct{ *Resolver }
type queriesResolver struct{ *Resolver }
type subscriptionsResolver struct{ *Resolver }
