// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/thanishsid/dingilink-server/internal/types"
)

type EmailVerificationToken struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Friendship struct {
	ID        int64
	UserID    int64
	FriendID  int64
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Group struct {
	ID          int64
	Name        string
	Image       *string
	Description *string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
}

type GroupMember struct {
	ID       int64
	GroupID  int64
	UserID   int64
	JoinedAt pgtype.Timestamptz
	IsAdmin  bool
}

type Message struct {
	ID                int64
	SenderID          int64
	RecipientID       *int64
	GroupID           *int64
	MessageType       string
	TextContent       *string
	Media             *string
	Location          types.Point
	ReplyForMessageID *int64
	SentAt            pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	DeletedBy         *int64
}

type MessageReaction struct {
	ID        int64
	MessageID int32
	UserID    int32
	Emoji     string
	ReactedAt pgtype.Timestamptz
}

type MessageReadReceipt struct {
	ID        int64
	MessageID int64
	UserID    int64
	ReadAt    pgtype.Timestamptz
}

type Permission struct {
	ID          int64
	Name        string
	Description *string
	SortIndex   int64
}

type Post struct {
	ID        int64
	Caption   *string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	SortIndex int32
}

type PostComment struct {
	ID       int64
	PostID   int64
	UserID   int64
	Content  string
	ParentID *int64
}

type PostCommentLike struct {
	ID            int64
	PostCommentID int64
	UserID        int64
	LikedAt       pgtype.Timestamptz
}

type PostLike struct {
	ID      int64
	PostID  int64
	UserID  int64
	LikedAt pgtype.Timestamptz
}

type PostMedium struct {
	ID        int64
	PostID    int64
	Media     string
	SortIndex int32
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	IssuedAt  pgtype.Timestamptz
}

type Role struct {
	ID          int64
	Name        string
	Description *string
	SortIndex   int64
}

type RolePermission struct {
	ID           int64
	RoleID       int64
	PermissionID *int64
}

type User struct {
	ID              int64
	Username        string
	Email           string
	Name            string
	PasswordHash    []byte
	Bio             *string
	Image           *string
	Online          bool
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type UserHierarchy struct {
	ID       int64
	ParentID int64
	ChildID  int64
}

type UserRole struct {
	ID     int64
	UserID int64
	RoleID int64
}
